import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://sangathan.space'

  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/dashboard/',
          '/admin/',
          '/api/',
          '/auth/',
          '/bootstrap-org/',
          '/maintenance/',
          '/select-organisation/',
        ],
      },
      {
        userAgent: [
          'Googlebot',
          'Bingbot',
          'Applebot',
          'DuckDuckBot',
          'YandexBot',
        ],
        allow: [
          '/',
          '/en/solutions/',
          '/hi/solutions/',
          '/en/compare/',
          '/hi/compare/',
          '/en/features',
          '/hi/features',
          '/en/pricing',
          '/hi/pricing',
          '/en/about',
          '/hi/about',
          '/en/transparency',
          '/hi/transparency',
          '/en/docs',
          '/hi/docs',
          '/en/org/',
          '/hi/org/',
          '/en/network/',
          '/hi/network/',
        ],
        disallow: ['/dashboard/', '/admin/', '/api/', '/auth/'],
      },
      {
        // Explicitly allow AI search & answer engines (Perplexity, ChatGPT Search, Claude, Gemini) to index all civic solutions, comparisons & documentation
        userAgent: [
          'GPTBot',
          'ChatGPT-User',
          'ClaudeBot',
          'PerplexityBot',
          'OAI-SearchBot',
          'cohere-ai',
          'Bytespider',
          'Google-Extended',
          'Diffbot',
          'FacebookBot',
        ],
        allow: [
          '/',
          '/en/solutions/',
          '/hi/solutions/',
          '/en/compare/',
          '/hi/compare/',
          '/en/org/',
          '/hi/org/',
          '/en/network/',
          '/hi/network/',
          '/en/features',
          '/hi/features',
          '/en/pricing',
          '/hi/pricing',
          '/en/about',
          '/hi/about',
          '/en/transparency',
          '/hi/transparency',
          '/en/docs',
          '/hi/docs',
          '/llms.txt',
          '/llms-full.txt',
        ],
        disallow: ['/dashboard/', '/admin/', '/api/', '/auth/'],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  }
}
