import { OrgType } from '@/lib/org-types'

export type BadgeTemplate = 'executive_seal' | 'social_graphic' | 'digital_id' | 'technical_minimalist' | 'tricolor_inquilab'
export type AspectRatio = '1:1' | '9:16' | '16:9' | 'cr80_id'
export type LanguageMode = 'en' | 'hi' | 'bilingual'

export interface OrgArchetypeConfig {
  nameEn: string
  nameHi: string
  ribbonHeaderEn: string
  ribbonHeaderHi: string
  statutoryTagEn: string
  statutoryTagHi: string
  defaultTheme: string
  defaultSymbol: string
  badgeTiers: Array<{ value: string; labelEn: string; labelHi: string }>
  defaultRoles: string[]
}

// 5 Sangathan Org Archetypes configuration
export const ORG_ARCHETYPES: Record<OrgType, OrgArchetypeConfig> = {
  civic_collective: {
    nameEn: 'Civic Collective & Grassroots Movement',
    nameHi: 'नागरिक समूह व जमीनी आंदोलन',
    ribbonHeaderEn: '✦ SANGATHAN VERIFIED CIVIC NETWORK • BAHUJAN QUEER FOUNDATION CERTIFIED ✦',
    ribbonHeaderHi: '✦ संगठन सत्यापित नागरिक नेटवर्क • बीक्यूएफ प्रमाणित ✦',
    statutoryTagEn: 'GRASSROOTS CIVIC ACTION NETWORK • UNREGISTERED COLLECTIVE',
    statutoryTagHi: 'जमीनी नागरिक नेटवर्क • जन सामूहिक पहल',
    defaultTheme: 'sovereign_navy',
    defaultSymbol: 'scales_of_justice',
    badgeTiers: [
      { value: 'Verified Constitutional & Civic Protector', labelEn: 'Verified Constitutional Protector', labelHi: 'सत्यापित संवैधानिक व नागरिक रक्षक' },
      { value: 'Verified Citizen Science Field Auditor', labelEn: 'Citizen Science Field Auditor', labelHi: 'नागरिक विज्ञान फील्ड ऑडिटर' },
      { value: 'Verified Environmental & Climate Defender', labelEn: 'Environmental & Climate Defender', labelHi: 'पर्यावरण व जलवायु रक्षक' },
      { value: 'Verified RTI & Legal Aid Volunteer', labelEn: 'RTI & Legal Aid Volunteer', labelHi: 'RTI व विधिक सहायता साथी' },
      { value: 'BQF Ground Fellow • Sec 8 Certified', labelEn: 'BQF Ground Fellow (Sec 8)', labelHi: 'BQF जमीनी साथी (धारा 8)' },
      { value: 'Grassroots Campaign Organizer', labelEn: 'Grassroots Campaign Organizer', labelHi: 'जमीनी अभियान संगठक' },
    ],
    defaultRoles: ['Active Member', 'Lead Organizer', 'Field Auditor', 'Legal Defense Coordinator', 'Area Convener', 'Volunteer'],
  },
  ngo: {
    nameEn: 'Registered Non-Governmental Org (NGO)',
    nameHi: 'पंजीकृत स्वयंसेवी संस्था (NGO)',
    ribbonHeaderEn: '✦ REGISTERED NGO • PUBLIC TRUST & TRANSPARENCY NETWORK ✦',
    ribbonHeaderHi: '✦ पंजीकृत गैर-सरकारी संगठन • लोक विश्वास व पारदर्शिता ✦',
    statutoryTagEn: 'SOCIETIES REG. ACT 1860 / SEC 8 NGO • 80G COMPLIANT LEDGER',
    statutoryTagHi: 'सोसाइटी पंजीकरण अधिनियम 1860 / धारा 8 NGO • 80G अनुपालित',
    defaultTheme: 'grassroots_emerald',
    defaultSymbol: 'open_book_sun',
    badgeTiers: [
      { value: 'Certified Humanitarian Volunteer', labelEn: 'Certified Humanitarian Volunteer', labelHi: 'प्रमाणित सेवादार / स्वयंसेवक' },
      { value: '80G Public Transparency & Compliance Officer', labelEn: '80G Transparency & Compliance Officer', labelHi: '80G पारदर्शिता व अनुपालन अधिकारी' },
      { value: 'Field Project Lead & Aid Worker', labelEn: 'Field Project Lead & Aid Worker', labelHi: 'फील्ड प्रोजेक्ट प्रभारी व राहत कर्मी' },
      { value: 'Public Trust & Community Fellow', labelEn: 'Public Trust & Community Fellow', labelHi: 'लोक विश्वास व समुदाय फेलो' },
      { value: 'Disaster Relief Rapid Responder', labelEn: 'Disaster Relief Rapid Responder', labelHi: 'आपदा राहत त्वरित प्रतिक्रिया दल' },
      { value: 'Executive Trustee & Board Member', labelEn: 'Executive Trustee & Board Member', labelHi: 'कार्यकारी ट्रस्टी व बोर्ड सदस्य' },
    ],
    defaultRoles: ['Volunteer', 'Project Coordinator', 'Program Director', 'Field Officer', 'Trustee', 'Executive Director'],
  },
  student_union: {
    nameEn: 'Democratic Student Union',
    nameHi: 'लोकतांत्रिक छात्र संघ',
    ribbonHeaderEn: '✦ DEMOCRATIC STUDENT UNION FEDERATION • LYNGDOH COMPLIANT ✦',
    ribbonHeaderHi: '✦ लोकतांत्रिक छात्र संघ महासंघ • लिंगदोह अनुपालित ✦',
    statutoryTagEn: 'DEMOCRATIC STUDENT BODY • UNIVERSITY STATUTE RECOGNIZED',
    statutoryTagHi: 'लोकतांत्रिक छात्र निकाय • विश्वविद्यालय अधिनियम मान्यता प्राप्त',
    defaultTheme: 'royal_indigo',
    defaultSymbol: 'quill_and_torch',
    badgeTiers: [
      { value: 'Elected Student Representative', labelEn: 'Elected Student Representative', labelHi: 'निर्वाचित छात्र प्रतिनिधि' },
      { value: 'Union President / Vice President', labelEn: 'Union President / Vice President', labelHi: 'संघ अध्यक्ष / उपाध्यक्ष' },
      { value: 'General Secretary & Central Councillor', labelEn: 'General Secretary & Central Councillor', labelHi: 'महासचिव व केंद्रीय पार्षद' },
      { value: 'Department / Hostel Councillor', labelEn: 'Department / Hostel Councillor', labelHi: 'विभाग / छात्रावास पार्षद' },
      { value: 'Campus Mess & Welfare Committee Lead', labelEn: 'Campus Mess & Welfare Lead', labelHi: 'मेस व छात्र कल्याण समिति प्रमुख' },
      { value: 'Anti-Ragging & Student Rights Delegate', labelEn: 'Student Rights & Anti-Ragging Delegate', labelHi: 'छात्र अधिकार व रैगिंग-रोधी प्रतिनिधि' },
    ],
    defaultRoles: ['General Secretary', 'President', 'Vice President', 'Department Councillor', 'Hostel Warden Rep', 'Cadre Member'],
  },
  workers_union: {
    nameEn: 'Workers Union & Trade Collective',
    nameHi: 'श्रमिक संघ व मजदूर संगठन',
    ribbonHeaderEn: '✦ SHRAMIK SANGATHAN • TRADE UNIONS ACT 1926 REGISTERED ✦',
    ribbonHeaderHi: '✦ श्रमिक संगठन • ट्रेड यूनियन अधिनियम 1926 पंजीकृत ✦',
    statutoryTagEn: 'REGISTERED TRADE UNION • COLLECTIVE BARGAINING BODY (CBA)',
    statutoryTagHi: 'पंजीकृत ट्रेड यूनियन • सामूहिक सौदेबाजी निकाय (CBA)',
    defaultTheme: 'inquilab_crimson',
    defaultSymbol: 'solidarity_fist',
    badgeTiers: [
      { value: 'Certified Shop Floor Steward', labelEn: 'Certified Shop Floor Steward', labelHi: 'प्रमाणित शॉप-फ्लोर प्रतिनिधि' },
      { value: 'Trade Union Delegate (CBA Negotiator)', labelEn: 'Trade Union Delegate (CBA)', labelHi: 'ट्रेड यूनियन प्रतिनिधि (CBA वार्ताकार)' },
      { value: 'Workplace Safety & Hazard Auditor', labelEn: 'Workplace Safety & Hazard Auditor', labelHi: 'कार्यस्थल सुरक्षा व श्रम परीक्षक' },
      { value: 'Strike & Welfare Relief Cadre', labelEn: 'Strike & Welfare Relief Cadre', labelHi: 'हड़ताल व मजदूर कल्याण कैडर' },
      { value: 'General Secretary / State Office Bearer', labelEn: 'General Secretary / State Bearer', labelHi: 'महासचिव / राज्य पदाधिकारी' },
      { value: 'Gig & Informal Sector Worker Steward', labelEn: 'Gig & Informal Sector Steward', labelHi: 'गिग व असंगठित मजदूर प्रतिनिधि' },
    ],
    defaultRoles: ['Shop Floor Steward', 'Union Delegate', 'General Secretary', 'Safety Warden', 'CBA Representative', 'Standing Member'],
  },
  rwa: {
    nameEn: 'Resident Welfare Association (RWA)',
    nameHi: 'आवासीय कल्याण संघ (RWA)',
    ribbonHeaderEn: '✦ RESIDENT WELFARE ASSOCIATION • REGISTERED COMMUNITY COUNCIL ✦',
    ribbonHeaderHi: '✦ आवासीय कल्याण संघ • पंजीकृत समुदाय परिषद ✦',
    statutoryTagEn: 'REGISTERED RWA • STATE COOPERATIVE & APARTMENT ACTS',
    statutoryTagHi: 'पंजीकृत आरडब्ल्यूए • राज्य सहकारी व अपार्टमेंट अधिनियम',
    defaultTheme: 'technical_slate',
    defaultSymbol: 'community_housing',
    badgeTiers: [
      { value: 'Elected Managing Committee Officer', labelEn: 'Elected Managing Committee Officer', labelHi: 'निर्वाचित प्रबंधन समिति अधिकारी' },
      { value: 'Block / Floor Action Representative', labelEn: 'Block / Floor Action Representative', labelHi: 'ब्लॉक व फ्लोर एक्शन प्रतिनिधि' },
      { value: 'Estate Maintenance & Asset Warden', labelEn: 'Estate Maintenance & Asset Warden', labelHi: 'सोसाइटी रखरखाव व संपत्ति वार्डन' },
      { value: 'Green, Solar & Sanitation Steward', labelEn: 'Green & Sanitation Steward', labelHi: 'हरित व स्वच्छता प्रभारी' },
      { value: 'Security & Gate Protocol Convener', labelEn: 'Security & Gate Protocol Convener', labelHi: 'सुरक्षा व गेट प्रोटोकॉल संयोजक' },
      { value: 'Senior Citizen & Community Care Rep', labelEn: 'Community Care Representative', labelHi: 'वरिष्ठ नागरिक व समुदाय सेवा साथी' },
    ],
    defaultRoles: ['President', 'General Secretary', 'Treasurer', 'Block Representative', 'Managing Committee Member', 'Resident Owner'],
  },
}

// 8 Rich Movement Themes
export const BADGE_THEMES = [
  {
    id: 'sovereign_navy',
    name: 'Democratic Navy & Gold',
    nameHi: 'लोकतांत्रिक नेवी व स्वर्ण',
    bgGradient: ['#090D16', '#141B2D'],
    cardBg: 'rgba(15, 23, 42, 0.92)',
    accent: '#F59E0B',
    accentLight: '#FDE68A',
    badgeBg: '#3B82F6',
    textColor: '#F8FAFC',
    subTextColor: '#94A3B8',
    cardBorder: '#334155',
    pillBg: 'rgba(245, 158, 11, 0.15)',
    pillBorder: '#F59E0B',
  },
  {
    id: 'tricolor_saffron',
    name: 'Constitution Tricolor (Saffron & Emerald)',
    nameHi: 'संविधान तिरंगा (केसरिया व हरा)',
    bgGradient: ['#FFFBF5', '#F0FDF4'],
    cardBg: 'rgba(255, 255, 255, 0.96)',
    accent: '#D97706',
    accentLight: '#F59E0B',
    badgeBg: '#15803D',
    textColor: '#0F172A',
    subTextColor: '#475569',
    cardBorder: '#CBD5E1',
    pillBg: 'rgba(217, 119, 6, 0.12)',
    pillBorder: '#D97706',
  },
  {
    id: 'grassroots_emerald',
    name: 'Grassroots Forest & Mint (NGO / Eco)',
    nameHi: 'जमीनी वन हरा व मिंट (एनजीओ)',
    bgGradient: ['#052E16', '#064E3B'],
    cardBg: 'rgba(6, 78, 59, 0.88)',
    accent: '#10B981',
    accentLight: '#6EE7B7',
    badgeBg: '#059669',
    textColor: '#F0FDF4',
    subTextColor: '#A7F3D0',
    cardBorder: '#065F46',
    pillBg: 'rgba(16, 185, 129, 0.2)',
    pillBorder: '#10B981',
  },
  {
    id: 'inquilab_crimson',
    name: 'Inquilab Crimson & Terracotta (Workers)',
    nameHi: 'इंकलाब लाल व टेराकोटा (मजदूर)',
    bgGradient: ['#3B0712', '#4C0519'],
    cardBg: 'rgba(40, 6, 15, 0.92)',
    accent: '#FB7185',
    accentLight: '#FDA4AF',
    badgeBg: '#E11D48',
    textColor: '#FFF1F2',
    subTextColor: '#FECDD3',
    cardBorder: '#881337',
    pillBg: 'rgba(251, 113, 133, 0.2)',
    pillBorder: '#FB7185',
  },
  {
    id: 'royal_indigo',
    name: 'Constitutional Indigo & Azure (Student)',
    nameHi: 'संवैधानिक इंडिगो व आसमानी (छात्र)',
    bgGradient: ['#0B0F2A', '#1E1B4B'],
    cardBg: 'rgba(30, 27, 75, 0.9)',
    accent: '#818CF8',
    accentLight: '#C7D2FE',
    badgeBg: '#4F46E5',
    textColor: '#EEF2FF',
    subTextColor: '#C7D2FE',
    cardBorder: '#3730A3',
    pillBg: 'rgba(129, 140, 248, 0.2)',
    pillBorder: '#818CF8',
  },
  {
    id: 'earth_terracotta',
    name: 'Earth Terracotta & Raw Amber',
    nameHi: 'धरती माटी व अंबर',
    bgGradient: ['#291305', '#451A03'],
    cardBg: 'rgba(41, 19, 5, 0.92)',
    accent: '#FBBF24',
    accentLight: '#FDE68A',
    badgeBg: '#B45309',
    textColor: '#FFFBEB',
    subTextColor: '#FDE68A',
    cardBorder: '#78350F',
    pillBg: 'rgba(251, 191, 36, 0.2)',
    pillBorder: '#FBBF24',
  },
  {
    id: 'technical_slate',
    name: 'Clean Technical Slate & Cyan',
    nameHi: 'तकनीकी स्लेट व स्यान',
    bgGradient: ['#F8FAFC', '#F1F5F9'],
    cardBg: 'rgba(255, 255, 255, 0.98)',
    accent: '#0284C7',
    accentLight: '#38BDF8',
    badgeBg: '#0F172A',
    textColor: '#0F172A',
    subTextColor: '#64748B',
    cardBorder: '#CBD5E1',
    pillBg: 'rgba(2, 132, 199, 0.1)',
    pillBorder: '#0284C7',
  },
  {
    id: 'ink_monochrome',
    name: 'Official Ink & Photostat Monochrome',
    nameHi: 'आधिकारिक स्याही मोनोक्रोम (फोटोस्टेट)',
    bgGradient: ['#FFFFFF', '#F4F4F5'],
    cardBg: 'rgba(255, 255, 255, 1)',
    accent: '#18181B',
    accentLight: '#3F3F46',
    badgeBg: '#09090B',
    textColor: '#09090B',
    subTextColor: '#52525B',
    cardBorder: '#27272A',
    pillBg: 'rgba(24, 24, 27, 0.08)',
    pillBorder: '#18181B',
  },
]
