import { FormTemplate } from '@/types/forms'

export const FORM_TEMPLATES: FormTemplate[] = [
  // --- NGO / Trust Templates ---
  {
    id: 'ngo_volunteer_intake',
    title: 'Volunteer Onboarding & Skills Intake',
    description: 'Collect volunteer availability, domain skills, and emergency contact details for social impact drives.',
    category: 'ngo',
    orgTypeLabel: 'NGO / Trust',
    fields: [
      { id: 'sec_personal', label: 'Personal Information', type: 'heading', required: false, description: 'Basic identification and contact details' },
      { id: 'full_name', label: 'Full Name', type: 'text', required: true, placeholder: 'e.g. Ananya Roy' },
      { id: 'phone', label: 'WhatsApp / Mobile Number', type: 'phone', required: true, placeholder: '+91 9876543210' },
      { id: 'email', label: 'Email Address', type: 'email', required: false, placeholder: 'ananya@example.com' },
      { id: 'city_area', label: 'Current City / District', type: 'text', required: true, placeholder: 'e.g. Pune, Maharashtra' },
      { id: 'sec_skills', label: 'Skills & Availability', type: 'heading', required: false, description: 'How you would like to contribute' },
      {
        id: 'skills',
        label: 'Domain Expertise / Skills',
        type: 'checkbox',
        required: true,
        options: ['Field Outreach & Relief Distribution', 'Content Writing & Social Media', 'Legal Aid & Documentation', 'Teaching & Child Tutoring', 'Fundraising & Event Coordination', 'Tech & Web Support'],
      },
      {
        id: 'availability_hours',
        label: 'Weekly Available Hours',
        type: 'radio',
        required: true,
        options: ['1-3 hours / week', '4-7 hours / week', '8-15 hours / week', 'Full-time / Intensive campaigns'],
      },
      { id: 'prior_experience', label: 'Briefly describe any prior social work experience', type: 'textarea', required: false, placeholder: 'Tell us about past NGO, student, or community initiatives you participated in...' },
      { id: 'motivation_rating', label: 'How excited are you to participate in our upcoming outreach?', type: 'rating', required: true, maxRating: 5 },
    ],
  },
  {
    id: 'ngo_beneficiary_needs',
    title: 'Community Relief & Beneficiary Needs Assessment',
    description: 'Ground survey to assess family income, ration needs, healthcare requirements, and relief priority.',
    category: 'ngo',
    orgTypeLabel: 'NGO / Trust',
    fields: [
      { id: 'sec_family', label: 'Family Profile', type: 'heading', required: false, description: 'Head of household identification' },
      { id: 'head_name', label: 'Head of Household Name', type: 'text', required: true, placeholder: 'e.g. Rameshwar Sahni' },
      { id: 'contact_phone', label: 'Contact Phone Number', type: 'phone', required: true, placeholder: '+91 9876543210' },
      { id: 'settlement_area', label: 'Slum / Basti / Village Name', type: 'text', required: true, placeholder: 'e.g. Sanjay Basti, Sector 4' },
      { id: 'family_members_count', label: 'Total Family Members (including children)', type: 'number', required: true, placeholder: 'e.g. 5' },
      { id: 'sec_requirements', label: 'Immediate Relief Needs', type: 'heading', required: false, description: 'Categorized essential support' },
      {
        id: 'relief_categories',
        label: 'Immediate Relief Required',
        type: 'checkbox',
        required: true,
        options: ['Dry Ration & Food Kits', 'Medical Aid & Essential Medicines', 'Children School Books & Stationery', 'Winter Blankets & Clothes', 'Livelihood Tool Kit (Cart, Sewing, etc.)'],
      },
      {
        id: 'urgency_level',
        label: 'Urgency Priority Level',
        type: 'scale',
        required: true,
        minLabel: '1 - Low / Routine',
        maxLabel: '5 - Critical Emergency',
      },
      { id: 'ration_card_available', label: 'Do you have an active Ration Card / Ayushman Card?', type: 'yes_no', required: true },
      { id: 'field_notes', label: 'Surveyor Field Observations / Notes', type: 'textarea', required: false, placeholder: 'Special medical conditions, housing structural risks, etc.' },
    ],
  },

  // --- Environmental Collective / Citizen Science (free for every org type) ---
  {
    id: 'env_air_quality_log',
    title: 'Citizen Air Quality Log (PM2.5 / PM10)',
    description: 'Daily citizen log of air readings with location and time — builds dated evidence for municipal complaints.',
    category: 'civic_collective',
    orgTypeLabel: 'Environmental Collective',
    fields: [
      { id: 'sec_site', label: 'Monitoring Site', type: 'heading', required: false, description: 'Where and when the reading was taken' },
      { id: 'site_area', label: 'Area / Landmark', type: 'text', required: true, placeholder: 'e.g. Anand Vihar, near bus depot' },
      { id: 'reading_date', label: 'Date of Reading', type: 'date', required: true },
      { id: 'sec_readings', label: 'Meter Readings', type: 'heading', required: false, description: 'From your handheld monitor or nearest station' },
      { id: 'pm25', label: 'PM2.5 (µg/m³)', type: 'number', required: true, placeholder: 'e.g. 180' },
      { id: 'pm10', label: 'PM10 (µg/m³)', type: 'number', required: false, placeholder: 'e.g. 260' },
      {
        id: 'smell_visibility',
        label: 'Visible Smog / Smell',
        type: 'radio',
        required: false,
        options: ['No smog', 'Light haze', 'Thick smog', 'Burning smell present'],
      },
      { id: 'health_notes', label: 'Health Complaints Noticed (Optional)', type: 'textarea', required: false, placeholder: 'e.g. children coughing at the park in the morning' },
      { id: 'reporter_phone', label: 'Reporter Phone (for verification)', type: 'phone', required: true, placeholder: '+91 9876543210' },
    ],
  },
  {
    id: 'env_water_tds_log',
    title: 'Drinking Water TDS & Quality Log',
    description: 'Log tap/handpump water TDS readings with source details — dated proof for water complaints.',
    category: 'civic_collective',
    orgTypeLabel: 'Environmental Collective',
    fields: [
      { id: 'sec_source', label: 'Water Source', type: 'heading', required: false, description: 'Which supply this reading belongs to' },
      { id: 'source_area', label: 'Area / Street / House No.', type: 'text', required: true, placeholder: 'e.g. Gali 4, Sangam Vihar' },
      {
        id: 'source_type',
        label: 'Source Type',
        type: 'radio',
        required: true,
        options: ['Municipal tap', 'Borewell / Handpump', 'Tanker supply', 'RO plant / community filter'],
      },
      { id: 'sec_reading', label: 'Meter Reading', type: 'heading', required: false, description: 'Use a handheld TDS meter (under ₹300)' },
      { id: 'tds_ppm', label: 'TDS (ppm)', type: 'number', required: true, placeholder: 'e.g. 420' },
      { id: 'smell_color', label: 'Bad smell or colour in water?', type: 'yes_no', required: true },
      { id: 'supply_hours', label: 'Daily Supply Hours (approx)', type: 'text', required: false, placeholder: 'e.g. 1 hour morning only' },
      { id: 'health_notes', label: 'Health Issues in Family (Optional)', type: 'textarea', required: false, placeholder: 'e.g. stomach upset twice this month' },
      { id: 'reporter_phone', label: 'Reporter Phone (for verification)', type: 'phone', required: true, placeholder: '+91 9876543210' },
    ],
  },
  {
    id: 'env_garbage_dump_report',
    title: 'Garbage Dump & Sanitation Report',
    description: 'Report overflowing dumps and broken sanitation with ward details for escalation.',
    category: 'civic_collective',
    orgTypeLabel: 'Environmental Collective',
    fields: [
      { id: 'sec_spot', label: 'Dump Spot', type: 'heading', required: false, description: 'Exact spot so trucks can find it' },
      { id: 'spot_location', label: 'Location / Landmark', type: 'text', required: true, placeholder: 'e.g. Behind DDA market, Sector 7' },
      { id: 'ward_no', label: 'Ward Number (if known)', type: 'text', required: false, placeholder: 'e.g. Ward 32' },
      {
        id: 'waste_types',
        label: 'Waste Types Seen',
        type: 'checkbox',
        required: true,
        options: ['Household garbage pile', 'Construction debris (malba)', 'Plastic burning', 'Dead animals', 'Hospital / medical waste', 'Overflowing dhalaos / bins'],
      },
      { id: 'days_pending', label: 'How many days has it been lying?', type: 'radio', required: true, options: ['1-2 days', '3-7 days', '1-4 weeks', 'More than a month'] },
      { id: 'mosquito_stray', label: 'Mosquito breeding / stray animal menace?', type: 'yes_no', required: false },
      { id: 'action_notes', label: 'What action do you demand?', type: 'textarea', required: true, placeholder: 'e.g. Daily lifting + one more dhalao near the park gate' },
      { id: 'reporter_phone', label: 'Reporter Phone (for verification)', type: 'phone', required: true, placeholder: '+91 9876543210' },
    ],
  },
  {
    id: 'env_tree_census',
    title: 'Tree Census & Green Cover Record',
    description: 'Record every tree with species and health — your green cover evidence for plantation and felling complaints.',
    category: 'civic_collective',
    orgTypeLabel: 'Environmental Collective',
    fields: [
      { id: 'sec_tree', label: 'Tree Identity', type: 'heading', required: false, description: 'One entry per tree' },
      { id: 'species', label: 'Species (Local Name OK)', type: 'text', required: true, placeholder: 'e.g. Neem / Peepal / Gulmohar' },
      { id: 'location', label: 'Location', type: 'text', required: true, placeholder: 'e.g. In front of house 214, left side' },
      { id: 'girth_cm', label: 'Trunk Girth in cm (approx, at chest height)', type: 'number', required: false, placeholder: 'e.g. 90' },
      {
        id: 'health',
        label: 'Tree Health',
        type: 'radio',
        required: true,
        options: ['Healthy & thriving', 'Needs watering / care', 'Damaged (nails, paint, concrete)', 'Dying / needs expert check', 'Illegally cut / missing'],
      },
      { id: 'threat_notes', label: 'Threats Noticed (Optional)', type: 'textarea', required: false, placeholder: 'e.g. concretization up to trunk, banners nailed on' },
      { id: 'reporter_phone', label: 'Reporter Phone (for verification)', type: 'phone', required: true, placeholder: '+91 9876543210' },
    ],
  },

  // --- Civic Collective / Grassroots Movement ---
  {
    id: 'civic_townhall_survey',
    title: 'Community Townhall & Public Issue Prioritization Poll',
    description: 'Democratic polling to identify top community struggles, local infrastructure priorities, and citizen mobilization.',
    category: 'civic_collective',
    orgTypeLabel: 'Civic Collective',
    fields: [
      { id: 'citizen_name', label: 'Citizen / Organizer Name', type: 'text', required: true, placeholder: 'e.g. Bilal Ahmed' },
      { id: 'ward_area', label: 'Ward / Mohalla / Neighborhood', type: 'text', required: true, placeholder: 'e.g. Ward 32, Shahdara' },
      { id: 'phone', label: 'WhatsApp Number for Campaign Updates', type: 'phone', required: true, placeholder: '+91 9876543210' },
      {
        id: 'top_issue',
        label: 'Most Pressing Issue in Your Ward',
        type: 'radio',
        required: true,
        options: ['Contaminated Drinking Water & Low Pressure', 'Broken Roads & Open Drains / Waterlogging', 'Lack of Public Park / Children Playground', 'Irregular Power Cuts & Voltage Fluctuations', 'Women Safety & Non-Functional Street Lights'],
      },
      {
        id: 'rep_satisfaction',
        label: 'Satisfaction with Local MLA / Councillor Response',
        type: 'scale',
        required: true,
        minLabel: '1 - Zero Action / Ignored',
        maxLabel: '5 - Responsive & Helpful',
      },
      { id: 'rally_attendance', label: 'Will you join our upcoming peaceful delegation to the Municipal Office?', type: 'yes_no', required: true },
      { id: 'citizen_voice', label: 'Share your personal experience / message for the joint petition', type: 'textarea', required: true, placeholder: 'How long has this issue persisted and how has it affected your family?' },
    ],
  },
]
