import { FormTemplate } from '@/types/forms'

export const FORM_TEMPLATES: FormTemplate[] = [
  // --- NGO / Trust Templates ---
  {
    id: 'ngo_volunteer_intake',
    title: 'Volunteer Onboarding & Skills Intake',
    description: 'Collect volunteer availability, domain skills, and emergency contact details for social impact drives.',
    category: 'ngo',
    orgTypeLabel: 'NGO / Trust',
    fields: [
      { id: 'sec_personal', label: 'Personal Information', type: 'heading', required: false, description: 'Basic identification and contact details' },
      { id: 'full_name', label: 'Full Name', type: 'text', required: true, placeholder: 'e.g. Ananya Roy' },
      { id: 'phone', label: 'WhatsApp / Mobile Number', type: 'phone', required: true, placeholder: '+91 9876543210' },
      { id: 'email', label: 'Email Address', type: 'email', required: false, placeholder: 'ananya@example.com' },
      { id: 'city_area', label: 'Current City / District', type: 'text', required: true, placeholder: 'e.g. Pune, Maharashtra' },
      { id: 'sec_skills', label: 'Skills & Availability', type: 'heading', required: false, description: 'How you would like to contribute' },
      {
        id: 'skills',
        label: 'Domain Expertise / Skills',
        type: 'checkbox',
        required: true,
        options: ['Field Outreach & Relief Distribution', 'Content Writing & Social Media', 'Legal Aid & Documentation', 'Teaching & Child Tutoring', 'Fundraising & Event Coordination', 'Tech & Web Support'],
      },
      {
        id: 'availability_hours',
        label: 'Weekly Available Hours',
        type: 'radio',
        required: true,
        options: ['1-3 hours / week', '4-7 hours / week', '8-15 hours / week', 'Full-time / Intensive campaigns'],
      },
      { id: 'prior_experience', label: 'Briefly describe any prior social work experience', type: 'textarea', required: false, placeholder: 'Tell us about past NGO, student, or community initiatives you participated in...' },
      { id: 'motivation_rating', label: 'How excited are you to participate in our upcoming outreach?', type: 'rating', required: true, maxRating: 5 },
    ],
  },
  {
    id: 'ngo_beneficiary_needs',
    title: 'Community Relief & Beneficiary Needs Assessment',
    description: 'Ground survey to assess family income, ration needs, healthcare requirements, and relief priority.',
    category: 'ngo',
    orgTypeLabel: 'NGO / Trust',
    fields: [
      { id: 'sec_family', label: 'Family Profile', type: 'heading', required: false, description: 'Head of household identification' },
      { id: 'head_name', label: 'Head of Household Name', type: 'text', required: true, placeholder: 'e.g. Rameshwar Sahni' },
      { id: 'contact_phone', label: 'Contact Phone Number', type: 'phone', required: true, placeholder: '+91 9876543210' },
      { id: 'settlement_area', label: 'Slum / Basti / Village Name', type: 'text', required: true, placeholder: 'e.g. Sanjay Basti, Sector 4' },
      { id: 'family_members_count', label: 'Total Family Members (including children)', type: 'number', required: true, placeholder: 'e.g. 5' },
      { id: 'sec_requirements', label: 'Immediate Relief Needs', type: 'heading', required: false, description: 'Categorized essential support' },
      {
        id: 'relief_categories',
        label: 'Immediate Relief Required',
        type: 'checkbox',
        required: true,
        options: ['Dry Ration & Food Kits', 'Medical Aid & Essential Medicines', 'Children School Books & Stationery', 'Winter Blankets & Clothes', 'Livelihood Tool Kit (Cart, Sewing, etc.)'],
      },
      {
        id: 'urgency_level',
        label: 'Urgency Priority Level',
        type: 'scale',
        required: true,
        minLabel: '1 - Low / Routine',
        maxLabel: '5 - Critical Emergency',
      },
      { id: 'ration_card_available', label: 'Do you have an active Ration Card / Ayushman Card?', type: 'yes_no', required: true },
      { id: 'field_notes', label: 'Surveyor Field Observations / Notes', type: 'textarea', required: false, placeholder: 'Special medical conditions, housing structural risks, etc.' },
    ],
  },

  // --- Student Union Templates ---
  {
    id: 'student_hostel_mess_survey',
    title: 'Hostel & Campus Mess Quality Satisfaction Survey',
    description: 'Evaluate campus hostel hygiene, drinking water, mess food nutrition, and maintenance responsiveness.',
    category: 'student_union',
    orgTypeLabel: 'Student Union',
    fields: [
      { id: 'sec_student_id', label: 'Student Identification', type: 'heading', required: false, description: 'Class and hostel details' },
      { id: 'student_name', label: 'Student Name', type: 'text', required: true, placeholder: 'e.g. Divya Prakash' },
      { id: 'roll_number', label: 'Enrollment / Roll Number', type: 'text', required: true, placeholder: 'e.g. 2024-MA-042' },
      { id: 'phone', label: 'WhatsApp Number', type: 'phone', required: true, placeholder: '+91 9876543210' },
      {
        id: 'hostel_wing',
        label: 'Hostel / Wing',
        type: 'dropdown',
        required: true,
        options: ['Ganga Hostel', 'Yamuna Hostel', 'Kaveri Hostel', 'Jhelum Hostel', 'Brahmaputra Hostel', 'Day Scholar / Off-Campus'],
      },
      { id: 'sec_ratings', label: 'Quality & Service Ratings', type: 'heading', required: false, description: 'Rate basic facilities on campus' },
      { id: 'mess_food_rating', label: 'Mess Food Taste & Nutrition Rating', type: 'rating', required: true, maxRating: 5 },
      {
        id: 'mess_cleanliness_scale',
        label: 'Dining Hall & Kitchen Cleanliness',
        type: 'scale',
        required: true,
        minLabel: '1 - Very Poor',
        maxLabel: '5 - Spotless Hygiene',
      },
      { id: 'drinking_water_issue', label: 'Are water coolers / RO purifiers frequently dysfunctional?', type: 'yes_no', required: true },
      {
        id: 'top_mess_grievance',
        label: 'Primary Grievance Area',
        type: 'radio',
        required: true,
        options: ['Undercooked / Low Quality Ingredients', 'Lack of Nutritious Diet / Fruits', 'Unclean Plates & Water Supply', 'High Extra Charges / Inaccurate Mess Bill', 'Timing & Staff Behavior'],
      },
      { id: 'detailed_suggestions', label: 'Suggestions for the Mess Committee & Student Union Representation', type: 'textarea', required: false, placeholder: 'Specific menu changes or immediate repairs needed...' },
    ],
  },
  {
    id: 'student_academic_grievance',
    title: 'Academic & Campus Facilities Grievance Intake',
    description: 'Log issues regarding timetable clashes, library books, lab equipment, or scholarship delays for union advocacy.',
    category: 'student_union',
    orgTypeLabel: 'Student Union',
    fields: [
      { id: 'student_name', label: 'Full Name', type: 'text', required: true, placeholder: 'e.g. Tanvi Malik' },
      { id: 'department', label: 'Department / Faculty', type: 'text', required: true, placeholder: 'e.g. Political Science / Law Faculty' },
      { id: 'phone', label: 'Contact Phone', type: 'phone', required: true, placeholder: '+91 9876543210' },
      {
        id: 'grievance_category',
        label: 'Grievance Category',
        type: 'dropdown',
        required: true,
        options: ['Scholarship / Fellowship Disbursement Delay', 'Library & Reading Hall Space Shortage', 'Lab Equipment & Computer Center Outage', 'Evaluation / Re-evaluation Discrepancy', 'Hostel Allotment & Seat Scarcity', 'Equal Opportunity / Harassment Redressal'],
      },
      { id: 'grievance_details', label: 'Detailed Description of the Issue', type: 'textarea', required: true, placeholder: 'Give complete context, dates of representation, and concerned administrative officer...' },
      {
        id: 'urgency',
        label: 'Issue Urgency',
        type: 'scale',
        required: true,
        minLabel: '1 - Low / Term End',
        maxLabel: '5 - Immediate Examination Risk',
      },
      { id: 'representation_filed', label: 'Have you already submitted an official letter to the Dean / Proctor?', type: 'yes_no', required: true },
    ],
  },

  // --- Workers Union Templates ---
  {
    id: 'workers_safety_hazard_report',
    title: 'Workplace Safety & Hazard Incident Intake',
    description: 'Confidential reporting of shop-floor hazards, faulty machinery, missing safety PPE, and overtime violations.',
    category: 'workers_union',
    orgTypeLabel: 'Workers Union',
    fields: [
      { id: 'sec_worker', label: 'Worker Details (Confidential with Union)', type: 'heading', required: false, description: 'Protected under Union Privilege' },
      { id: 'worker_name', label: 'Worker Name / Employee No.', type: 'text', required: true, placeholder: 'e.g. Satish Kumar (ID: 4120)' },
      { id: 'phone', label: 'Mobile Number', type: 'phone', required: true, placeholder: '+91 9876543210' },
      { id: 'plant_unit', label: 'Plant / Shop Floor / Unit Name', type: 'text', required: true, placeholder: 'e.g. Assembly Line B, Plant 2' },
      {
        id: 'employment_type',
        label: 'Employment Status',
        type: 'radio',
        required: true,
        options: ['Permanent Union Member', 'Contract / Theka Worker', 'Apprentice / Trainee', 'Gig / Delivery Worker'],
      },
      { id: 'sec_hazard', label: 'Incident & Safety Violation', type: 'heading', required: false, description: 'What occurred at the workplace' },
      {
        id: 'hazard_type',
        label: 'Type of Safety Hazard / Violation',
        type: 'checkbox',
        required: true,
        options: ['Lack of Safety Gear (Helmets, Gloves, Shoes)', 'Faulty Machine Sensors / Missing Guards', 'Extreme Heat, Dust or Chemical Fumes', 'Forced Unpaid Overtime (>8 Hours)', 'Refusal of Medical First-Aid / ESI Denial'],
      },
      {
        id: 'severity_rating',
        label: 'Risk Severity to Life & Health',
        type: 'scale',
        required: true,
        minLabel: '1 - Minor Inconvenience',
        maxLabel: '5 - Severe Life Threat / Injury Risk',
      },
      { id: 'incident_description', label: 'Describe the Incident / Condition in Detail', type: 'textarea', required: true, placeholder: 'When did it happen, which machine/supervisor was involved, was anyone hurt?' },
      { id: 'supervisor_notified', label: 'Was the Supervisor / Safety Officer notified in writing?', type: 'yes_no', required: true },
    ],
  },
  {
    id: 'workers_cba_survey',
    title: 'Charter of Demands (CBA) Priority Survey',
    description: 'Gather member consensus on wage hike percentages, DA revision, medical allowances, and working condition priorities.',
    category: 'workers_union',
    orgTypeLabel: 'Workers Union',
    fields: [
      { id: 'member_name', label: 'Worker Name', type: 'text', required: true, placeholder: 'e.g. Rajesh Yadav' },
      { id: 'phone', label: 'Phone Number', type: 'phone', required: true, placeholder: '+91 9876543210' },
      { id: 'years_service', label: 'Years of Service in Organisation', type: 'number', required: true, placeholder: 'e.g. 6' },
      {
        id: 'top_priority',
        label: 'Most Critical Demand for Next Negotiation',
        type: 'radio',
        required: true,
        options: ['Base Wage Increase (₹ Minimum 20%)', 'DA / Dearness Allowance Revision', 'Equal Pay for Contract Workers', 'ESI / Enhanced Health Insurance for Family', 'Pension & Gratuity Enhancement', 'Safe Transport & Night Shift Allowances'],
      },
      { id: 'wage_satisfaction', label: 'Current Satisfaction with Management Compensation', type: 'rating', required: true, maxRating: 5 },
      { id: 'strike_readiness', label: 'Are you prepared to join a 2-day warning strike if negotiations stall?', type: 'yes_no', required: true },
      { id: 'additional_demands', label: 'Additional Working Condition Suggestions', type: 'textarea', required: false, placeholder: 'Canteen food subsidies, bonus timeline, uniform quality...' },
    ],
  },

  // --- RWA / Resident Society Templates ---
  {
    id: 'rwa_maintenance_safai_survey',
    title: 'Colony Security, Safai & Maintenance Satisfaction Survey',
    description: 'Survey resident opinion on garbage collection, CCTV security, lift maintenance, park lighting, and RWA transparency.',
    category: 'rwa',
    orgTypeLabel: 'RWA / Resident Society',
    fields: [
      { id: 'sec_resident', label: 'Resident Details', type: 'heading', required: false, description: 'Flat and block identity' },
      { id: 'resident_name', label: 'Resident Name', type: 'text', required: true, placeholder: 'e.g. Sunita Aggarwal' },
      { id: 'flat_number', label: 'Flat / House Number', type: 'text', required: true, placeholder: 'e.g. B-402, Block 4' },
      { id: 'phone', label: 'Mobile / WhatsApp', type: 'phone', required: true, placeholder: '+91 9876543210' },
      {
        id: 'occupancy_type',
        label: 'Occupancy Type',
        type: 'radio',
        required: true,
        options: ['Owner-Resident', 'Tenant / Rented Resident', 'Commercial Shop Owner'],
      },
      { id: 'sec_feedback', label: 'Colony Service Ratings', type: 'heading', required: false, description: 'Rate current society management' },
      { id: 'overall_satisfaction', label: 'Overall RWA Colony Management Satisfaction', type: 'rating', required: true, maxRating: 5 },
      {
        id: 'security_rating',
        label: 'Gate Security & Guard Vigilance',
        type: 'scale',
        required: true,
        minLabel: '1 - Inadequate / Careless',
        maxLabel: '5 - Very Vigilant & Safe',
      },
      {
        id: 'safai_frequency',
        label: 'Daily Door-to-Door Garbage Collection',
        type: 'radio',
        required: true,
        options: ['Timely & Regular Everyday', 'Frequently Missed / Irregular', 'Poor Segregation / Unhygienic Collection'],
      },
      { id: 'stray_animal_issue', label: 'Are stray dogs / parking congestion serious issues in your lane?', type: 'yes_no', required: true },
      { id: 'improvement_suggestions', label: 'Specific Improvements for General Body Meeting (AGM)', type: 'textarea', required: false, placeholder: 'Suggestions on park maintenance, EV charging spots, CCTV cameras...' },
    ],
  },
  {
    id: 'rwa_resident_census',
    title: 'Resident Census & Directory Registration',
    description: 'Register resident household information, vehicle numbers, and emergency contact details for society security.',
    category: 'rwa',
    orgTypeLabel: 'RWA / Resident Society',
    fields: [
      { id: 'full_name', label: 'Resident Name', type: 'text', required: true, placeholder: 'e.g. Harpreet Singh' },
      { id: 'flat_wing', label: 'Flat / Villa / Wing No.', type: 'text', required: true, placeholder: 'e.g. Tower 3, Flat 904' },
      { id: 'phone', label: 'Primary Contact Mobile', type: 'phone', required: true, placeholder: '+91 9876543210' },
      { id: 'email', label: 'Email for Society Notices & Maintenance Invoices', type: 'email', required: false, placeholder: 'harpreet@example.com' },
      { id: 'vehicles_count', label: 'Number of Four-Wheelers & Two-Wheelers Owned', type: 'number', required: true, placeholder: 'e.g. 2' },
      { id: 'emergency_contact_phone', label: 'Emergency Alternate Contact Phone', type: 'phone', required: true, placeholder: '+91 9811223344' },
      { id: 'intercom_active', label: 'Is your society intercom connection functional?', type: 'yes_no', required: true },
      { id: 'notes', label: 'Special Instructions (Senior Citizens, Medical Support, etc.)', type: 'textarea', required: false, placeholder: 'Senior citizen living alone, wheelchair ramp needed, etc.' },
    ],
  },

  // --- Civic Collective / Grassroots Movement ---
  {
    id: 'civic_townhall_survey',
    title: 'Community Townhall & Public Issue Prioritization Poll',
    description: 'Democratic polling to identify top community struggles, local infrastructure priorities, and citizen mobilization.',
    category: 'civic_collective',
    orgTypeLabel: 'Civic Collective',
    fields: [
      { id: 'citizen_name', label: 'Citizen / Organizer Name', type: 'text', required: true, placeholder: 'e.g. Bilal Ahmed' },
      { id: 'ward_area', label: 'Ward / Mohalla / Neighborhood', type: 'text', required: true, placeholder: 'e.g. Ward 32, Shahdara' },
      { id: 'phone', label: 'WhatsApp Number for Campaign Updates', type: 'phone', required: true, placeholder: '+91 9876543210' },
      {
        id: 'top_issue',
        label: 'Most Pressing Issue in Your Ward',
        type: 'radio',
        required: true,
        options: ['Contaminated Drinking Water & Low Pressure', 'Broken Roads & Open Drains / Waterlogging', 'Lack of Public Park / Children Playground', 'Irregular Power Cuts & Voltage Fluctuations', 'Women Safety & Non-Functional Street Lights'],
      },
      {
        id: 'rep_satisfaction',
        label: 'Satisfaction with Local MLA / Councillor Response',
        type: 'scale',
        required: true,
        minLabel: '1 - Zero Action / Ignored',
        maxLabel: '5 - Responsive & Helpful',
      },
      { id: 'rally_attendance', label: 'Will you join our upcoming peaceful delegation to the Municipal Office?', type: 'yes_no', required: true },
      { id: 'citizen_voice', label: 'Share your personal experience / message for the joint petition', type: 'textarea', required: true, placeholder: 'How long has this issue persisted and how has it affected your family?' },
    ],
  },
]
